
import java.time.LocalTime;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author javaspringboot
 */
public class Main extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Main.class.getName());
    
    

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        carEntranceBtn = new javax.swing.JButton();
        exitVehiculeBtn = new javax.swing.JButton();
        memberships = new javax.swing.JButton();
        boxBtn = new javax.swing.JButton();
        reportsBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        carEntranceBtn.setText("Ingreso de vehiculo");
        carEntranceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carEntranceBtnActionPerformed(evt);
            }
        });

        exitVehiculeBtn.setText("Salida de vehiculo");
        exitVehiculeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitVehiculeBtnActionPerformed(evt);
            }
        });

        memberships.setText("Membresias");

        boxBtn.setText("Cajas");

        reportsBtn.setText("Reportes");
        reportsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportsBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(356, 356, 356)
                        .addComponent(boxBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(317, 317, 317)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(exitVehiculeBtn)
                            .addComponent(carEntranceBtn)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(336, 336, 336)
                        .addComponent(memberships))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(346, 346, 346)
                        .addComponent(reportsBtn)))
                .addContainerGap(353, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(carEntranceBtn)
                .addGap(18, 18, 18)
                .addComponent(exitVehiculeBtn)
                .addGap(26, 26, 26)
                .addComponent(memberships)
                .addGap(29, 29, 29)
                .addComponent(boxBtn)
                .addGap(29, 29, 29)
                .addComponent(reportsBtn)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reportsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportsBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reportsBtnActionPerformed

    private void carEntranceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carEntranceBtnActionPerformed
        
        //Plate logic
        String plate = null;
        
        boolean tookMoreThanThreeAttempts = false;
        
        int i;
        for(i = 0; i < 3;i++){
            plate = JOptionPane.showInputDialog(rootPane, "Ingrese la placa del vehiculo", "Ventana",JOptionPane.QUESTION_MESSAGE).trim();

            if(plate == null) return;

            if(plate.contains(" ")){
                JOptionPane.showMessageDialog(rootPane, "La placa no puede contener espacios", "Advertencia", JOptionPane.WARNING_MESSAGE);
                continue;
            }

            if(plate.length()!=6){
                JOptionPane.showMessageDialog(rootPane, "La placa tiene que ser de 6 caracteres", "Advertencia", JOptionPane.WARNING_MESSAGE);
                continue;
            }

            if(Parking.vehiclesParked.contains(plate)){
                JOptionPane.showMessageDialog(rootPane, "El vehiculo con placa " + plate + " ya se encuentra parqueado", "Advertencia", JOptionPane.WARNING_MESSAGE);
            } else {
                break;
            }
        }
        
        if(i==3){
            tookMoreThanThreeMethod();
            return;
        }
            
            
        
        
        //Type of vehicle logic
        
        
        Object[] typesOfVehicle = {"CARRO","MOTO","CAMIONETA"};
        
        String optionTypeVehicule = (String) JOptionPane.showInputDialog(rootPane, "Seleccione el tipo de vehiculo", "Ventana", JOptionPane.QUESTION_MESSAGE,null,typesOfVehicle,typesOfVehicle[0]);
        
        int valuePerHour = 0;
                
        if(optionTypeVehicule==null) return;

        if(optionTypeVehicule.equals("CARRO")){
            valuePerHour = 4000;
        } else if(optionTypeVehicule.equals("MOTO")){
            valuePerHour = 2500;
        } else {
            valuePerHour = 5500;
        }
        
        
        
        //Logic of the floor
        
        ArrayList<Integer> floorsAvailable = new ArrayList<>();
        for(int p = 0;p<4;p++){
            if(Parking.spacesAvailablePerFloor[p]>0){
                floorsAvailable.add(p+1);
            }
        }
        Object[] floors = floorsAvailable.toArray(new Integer[0]);
        
        Integer optionFloor = (Integer)JOptionPane.showInputDialog(
            rootPane,
            "Seleccione el piso donde se estacionara",
            "Ventana",
            JOptionPane.QUESTION_MESSAGE,
            null,
            floors,
            floors[0]
        );
        
        int optionFloorNumber;
        
        if(optionFloor==null){
            return;
        } else {
            optionFloorNumber = optionFloor;
        }

        
        //Entrance hour logic
        
        
        String entranceHour;
        int o;
        for(o = 0; o<3; o++){
            entranceHour = JOptionPane.showInputDialog(rootPane, "Ingrese la hora de entrada en el formato HH:mm\nEjemplo(08:30)", "Ventana", JOptionPane.QUESTION_MESSAGE);
            
            if(entranceHour == null)return;
            
            LocalTime timeEntrance = Parking.parseTime(entranceHour);
            
            if(timeEntrance==null){
                JOptionPane.showMessageDialog(rootPane, "Hora no valida", "Error", JOptionPane.ERROR_MESSAGE);
            }else{
                break;
            }
            
           
        }
        
        if(o==3){
           tookMoreThanThreeMethod();
           return;
        }

        
        
    }//GEN-LAST:event_carEntranceBtnActionPerformed

    private void exitVehiculeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitVehiculeBtnActionPerformed
        if(Parking.vehiclesParked.size()==0){
            JOptionPane.showMessageDialog(rootPane, "No hay vehiculos parqueados", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String plate = JOptionPane.showInputDialog(rootPane, "Ingrese la placa del vehiculo que desea retirar", "Ventana", JOptionPane.QUESTION_MESSAGE);
        
        if(plate==null)return;
        
        
        boolean passRetireHour = false;
        String retireHour;
        LocalTime timeExit;
        do{
            retireHour = JOptionPane.showInputDialog(rootPane, "Ingrese la hora de salida en el formato HH:mm\nEjemplo(08:30)", "Ventana", JOptionPane.QUESTION_MESSAGE);
            
            if(retireHour == null)return;
            
            timeExit = Parking.parseTime(retireHour);
            
            if(timeExit==null){
                JOptionPane.showMessageDialog(rootPane, "Hora no valida", "Error", JOptionPane.ERROR_MESSAGE);
            }else{
                break;
            }
            
           
        }while(!passRetireHour);
        
        int answerWeekend = JOptionPane.showConfirmDialog(rootPane, "¿Es sabado o domingo?", "Confirmacion",JOptionPane.YES_NO_OPTION);
        boolean isWeekend;
        
        if(answerWeekend==0){
            isWeekend = true;
        } else if(answerWeekend==1){
            isWeekend = false;
        } else {
            return;
        }
        
        
        
    }//GEN-LAST:event_exitVehiculeBtnActionPerformed

    public void tookMoreThanThreeMethod(){
        JOptionPane.showMessageDialog(rootPane, "Superaste los 3 intentos", "Informacion", JOptionPane.INFORMATION_MESSAGE);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Main().setVisible(true));
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boxBtn;
    private javax.swing.JButton carEntranceBtn;
    private javax.swing.JButton exitVehiculeBtn;
    private javax.swing.JButton memberships;
    private javax.swing.JButton reportsBtn;
    // End of variables declaration//GEN-END:variables
}


/*
// 1. Entrance of vehicles
        ArrayList<Vehicle> vehiclesParked = new ArrayList<>();

        // 4. Box

        int ticketsCar = 0;
        int finesCar = 0;
        int discountsCar = 0;
        int surchargesCar = 0;

        int ticketsMotorcycle = 0;
        int finesMotorcycle = 0;
        int discountsMotorcycle = 0;
        int surchargesMotorcycle = 0;

        int ticketsTruck = 0;
        int finesTruck = 0;
        int discountsTruck = 0;
        int surchargesTruck = 0;

        int totalShift = 0;


        // 5. reports

        double[] hoursStayedCar = {};
        double[] hoursStayedMotorcycle = {};
        double[] hoursStayedTruck = {};

        int levelOneAvailable = 30;
        int levelTwoAvailable = 40;
        int levelThreeAvailable = 40;
        int levelFourAvailable = 50;
*/